import React, { useEffect, useRef, useState } from 'react';
import {UserCircle, FileText, Download, Copy, Stethoscope, Smile, Award, Brain, TestTube, Users, Pencil } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Message } from '../types';
import { formatTime } from '../utils/date';
import jsPDF from 'jspdf';

interface ChatMessageProps {
  message: Message;
  onPreviewClick?: (fileUrl: string, fileType: string, fileName: string) => void;
  onEdit?: (id: string) => void;
  /** Show upload progress bar below the image (for the message that is currently uploading) */
  showUploadProgress?: boolean;
  uploadProgress?: number;
  analyzing?: boolean;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message, onPreviewClick, onEdit, showUploadProgress, uploadProgress = 0, analyzing }) => {
  const isUser = message.role === 'user';
  // File preview logic
  const isImage = message.fileUrl && message.fileType && message.fileType.startsWith('image/');
  const isPDF = message.fileType === 'application/pdf';
  const hasPdfThumbnail = !!message.pdfThumbnail;
  const messageRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);

  // Fade-in animation on mount
  useEffect(() => {
    if (messageRef.current) {
      messageRef.current.classList.add('fade-in');
    }
  }, []);

  useEffect(() => {
    if (copied) {
      const timer = setTimeout(() => setCopied(false), 1200);
      return () => clearTimeout(timer);
    }
  }, [copied]);
  
  // Helper to get formatted date/time
  const getFormattedDate = () => {
    const d = new Date(message.timestamp);
    return d.toLocaleString();
  };
  // Helper to get topic or file name
  const getTopic = () => {
    if (message.fileName) return message.fileName;
    return '';
  };
  // Download as PDF
  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text('Healthcare Assistant Interpretation', 10, 15);
    doc.setFontSize(10);
    doc.text(`Date: ${getFormattedDate()}`, 10, 25);
    const topic = getTopic();
    if (topic) doc.text(`Session/Topic: ${topic}`, 10, 32);
    doc.setFontSize(12);
    doc.text('---', 10, 40);
    doc.text(message.content, 10, 50, { maxWidth: 180 });
    doc.setFontSize(10);
    doc.text('---', 10, 270);
    doc.text('This summary was generated by an AI healthcare assistant for informational purposes only.', 10, 278, { maxWidth: 180 });
    doc.save(`AI-Interpretation-${message.id}.pdf`);
  };
  // Download as text
  const handleDownloadText = () => {
    const lines = [
      'Healthcare Assistant Interpretation',
      `Date: ${getFormattedDate()}`,
      getTopic() ? `Session/Topic: ${getTopic()}` : '',
      '---',
      message.content,
      '---',
      'This summary was generated by an AI healthcare assistant for informational purposes only.'
    ].filter(Boolean).join('\n');
    const blob = new Blob([lines], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AI-Interpretation-${message.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };
  // Copy to clipboard
  const handleCopy = () => {
    navigator.clipboard.writeText(message.content);
    setCopied(true);
  };
  
  return (
    <div
      ref={messageRef}
      className={`flex items-start space-x-3 ${isUser ? 'justify-end' : ''} message-spacing message-container performance-optimized`}
      style={{ animation: 'fadeInUp 0.5s' }}
    >
      {!isUser && (
        <div className="flex-shrink-0 bg-gradient-to-br from-blue-500 to-blue-700 rounded-full p-3 shadow-lg border-2 border-blue-200">
          <Stethoscope size={24} className="text-white" />
        </div>
      )}
      <div
        className={
          `p-4 rounded-2xl max-w-[85%] relative group shadow-lg transition-all duration-200 ` +
          `${isUser ? 'bg-gradient-to-br from-blue-500 to-blue-300 text-white rounded-tr-md' : 'bg-white text-gray-800 rounded-tl-md border border-gray-100'} ` +
          `${message.isError ? 'bg-red-50 text-red-800 border borde r-red-200' : ''}`
        }
      >
        <div className={`pb-1 mb-1 text-xs font-medium ${isUser ? 'text-primary-100' : 'text-gray-400'}`}
          style={{ letterSpacing: '0.02em' }}
        >
          {isUser ? 'You' : 'Healthcare Assistant'} • {formatTime(message.timestamp)}
        </div>
        {/* File preview for uploads */}
        {isUser && isImage && (
          <div className="mb-2">
            <button
              type="button"
              className="focus:outline-none"
              onClick={() => onPreviewClick && message.fileUrl && message.fileType && message.fileName && onPreviewClick(message.fileUrl, message.fileType, message.fileName)}
            >
              <img src={message.fileUrl} alt={message.fileName || 'Uploaded image'} className="max-h-40 rounded shadow border hover:scale-105 transition-transform" />
            </button>
            <div className="text-xs text-gray-200 mt-1 truncate">{message.fileName}</div>
            {(showUploadProgress || analyzing) && (
              <div className="mt-2 w-full space-y-1">
                {showUploadProgress && (
                  <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                    <div className="h-full bg-primary-500 transition-all duration-300" style={{ width: `${uploadProgress}%` }} />
                  </div>
                )}
                {analyzing && (
                  <p className="text-xs text-gray-300">Analyzing...</p>
                )}
              </div>
            )}
          </div>
        )}
        {isUser && isPDF && (
          <div className="mb-2">
            {hasPdfThumbnail ? (
              <button
                type="button"
                className="flex flex-col items-center focus:outline-none"
                onClick={() => onPreviewClick && message.fileUrl && message.fileType && message.fileName && onPreviewClick(message.fileUrl, message.fileType, message.fileName)}
              >
                <img src={message.pdfThumbnail} alt={message.fileName || 'PDF preview'} className="max-h-32 rounded shadow border mb-1" />
                <span className="text-xs text-gray-200 truncate">{message.fileName}</span>
              </button>
            ) : (
              <button
                type="button"
                className="flex items-center gap-2 focus:outline-none"
                onClick={() => onPreviewClick && message.fileUrl && message.fileType && message.fileName && onPreviewClick(message.fileUrl, message.fileType, message.fileName)}
              >
                <FileText size={28} className="text-primary-200" />
                <span className="text-xs text-gray-200 truncate">{message.fileName}</span>
              </button>
            )}
            {(showUploadProgress || analyzing) && (
              <div className="mt-2 w-full space-y-1">
                {showUploadProgress && (
                  <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                    <div className="h-full bg-primary-500 transition-all duration-300" style={{ width: `${uploadProgress}%` }} />
                  </div>
                )}
                {analyzing && (
                  <p className="text-xs text-gray-300">Analyzing...</p>
                )}
              </div>
            )}
          </div>
        )}
        {isUser ? (
          message.content ? <p className="whitespace-pre-wrap text-base leading-relaxed content-stable streaming-content">{message.content}</p> : null
        ) : (
          <>
            <div className="streaming-content content-stable prose prose-sm max-w-none prose-p:mb-1 prose-p:leading-relaxed">
              <div className="text-sm" style={{ wordWrap: 'break-word' }}>
                <ReactMarkdown
                  components={{
                    p: ({ node, ...props }) => <p {...props} className="mb-1 leading-relaxed whitespace-pre-wrap" style={{ whiteSpace: 'pre-wrap' }} />,
                    h2: ({ node, ...props }) => <h2 {...props} className="text-base font-semibold text-gray-900 mt-3 mb-1 first:mt-0" />,
                    h3: ({ node, ...props }) => <h3 {...props} className="text-sm font-medium text-gray-800 mt-2 mb-0.5" />,
                    strong: ({ node, ...props }) => <strong {...props} className="font-semibold text-gray-900" />,
                    em: ({ node, ...props }) => <em {...props} className="italic" />,
                  }}
                >
                  {message.content}
                </ReactMarkdown>
              </div>
            </div>
            {/* Download/Copy buttons for assistant messages */}
            <div className="flex gap-1 mt-2 justify-end relative">
              <button
                className="p-1 rounded hover:bg-primary-100"
                title="Download as PDF"
                onClick={handleDownloadPDF}
              >
                <Download size={16} />
              </button>
              <button
                className="p-1 rounded hover:bg-primary-100"
                title="Download as Text"
                onClick={handleDownloadText}
              >
                <FileText size={16} />
              </button>
              <div className="relative">
                <button
                  className="p-1 rounded hover:bg-primary-100"
                  title="Copy to Clipboard"
                  onClick={handleCopy}
                >
                  <Copy size={16} />
                </button>
                {copied && (
                  <span className="absolute -top-7 left-1/2 -translate-x-1/2 bg-primary-600 text-white text-xs px-2 py-1 rounded shadow z-10 whitespace-nowrap">
                    Copied!
                  </span>
                )}
              </div>
            </div>
          </>
        )}
        {isUser && onEdit && (
          <button
            className="absolute top-2 right-2 text-white-700 hover:text-green-400"
            title="Edit message"
            aria-label="Edit message"
            onClick={() => onEdit(message.id)}
          >
            <Pencil size={16} />
          </button>
        )}
      </div>
      {isUser && (
        <div className="flex-shrink-0 bg-primary-500 rounded-full p-2 shadow-md border-2 border-primary-600">
          <Smile size={24} className="text-white" />
        </div>
      )}
    </div>
  );
};

export default ChatMessage;