import React, { useEffect, useRef, useState } from 'react';
import { FileText, Download, Copy, Stethoscope, Smile, Pencil } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Message } from '../types';
import { formatTime } from '../utils/date';
import { buildStaffReportPlainText, downloadStaffInterpretationPdf, StaffReportType } from '../utils/staffReportPdf';
import { createStaffMarkdownComponents } from '../utils/staffMarkdownComponents';

interface ChatMessageProps {
  message: Message;
  variant?: 'default' | 'staff';
  /** When set, PDF/text downloads use the radiology or laboratory report template */
  reportType?: StaffReportType;
  onPreviewClick?: (fileUrl: string, fileType: string, fileName: string) => void;
  onEdit?: (id: string) => void;
  /** Show upload progress bar below the image (for the message that is currently uploading) */
  showUploadProgress?: boolean;
  uploadProgress?: number;
  analyzing?: boolean;
}

const ChatMessage: React.FC<ChatMessageProps> = ({
  message,
  variant = 'default',
  reportType,
  onPreviewClick,
  onEdit,
  showUploadProgress,
  uploadProgress = 0,
  analyzing,
}) => {
  const isUser = message.role === 'user';
  const isStaff = variant === 'staff';
  const markdownComponents = createStaffMarkdownComponents({ isStaff });
  const effectiveReportType: StaffReportType =
    reportType ?? (isStaff ? 'general' : 'general');
  // File preview logic
  const isImage = message.fileUrl && message.fileType && message.fileType.startsWith('image/');
  const isPDF = message.fileType === 'application/pdf';
  const hasPdfThumbnail = !!message.pdfThumbnail;
  const messageRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);

  // Fade-in animation on mount
  useEffect(() => {
    if (messageRef.current) {
      messageRef.current.classList.add('fade-in');
    }
  }, []);

  useEffect(() => {
    if (copied) {
      const timer = setTimeout(() => setCopied(false), 1200);
      return () => clearTimeout(timer);
    }
  }, [copied]);
  
  // Helper to get formatted date/time
  const getFormattedDate = () => {
    const d = new Date(message.timestamp);
    return d.toLocaleString();
  };
  // Helper to get topic or file name
  const getTopic = () => {
    if (message.fileName) return message.fileName;
    return '';
  };
  const reportPdfOptions = () => ({
    content: message.content,
    reportType: effectiveReportType,
    messageId: message.id,
    timestamp: message.timestamp,
    sourceFileName: getTopic() || undefined,
  });

  const handleDownloadPDF = () => {
    if (isStaff && (effectiveReportType === 'radiology' || effectiveReportType === 'lab')) {
      downloadStaffInterpretationPdf(reportPdfOptions());
      return;
    }
    downloadStaffInterpretationPdf({
      ...reportPdfOptions(),
      reportType: 'general',
    });
  };

  const handleDownloadText = () => {
    const text =
      isStaff && (effectiveReportType === 'radiology' || effectiveReportType === 'lab')
        ? buildStaffReportPlainText(reportPdfOptions())
        : [
            'Healthcare Assistant Interpretation',
            `Date: ${getFormattedDate()}`,
            getTopic() ? `Session/Topic: ${getTopic()}` : '',
            '---',
            message.content,
            '---',
            'This summary was generated by an AI healthcare assistant for informational purposes only.',
          ]
            .filter(Boolean)
            .join('\n');
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AI-Interpretation-${message.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };
  // Copy to clipboard
  const handleCopy = () => {
    navigator.clipboard.writeText(message.content);
    setCopied(true);
  };
  
  return (
    <div
      ref={messageRef}
      className={`flex items-start space-x-3 ${isUser ? 'justify-end' : ''} message-spacing message-container performance-optimized`}
      style={{ animation: 'fadeInUp 0.5s' }}
    >
      {!isUser && (
        <div
          className={
            isStaff
              ? 'flex-shrink-0 rounded-full border border-sky-500/30 bg-sky-500/20 p-3 shadow-lg'
              : 'flex-shrink-0 rounded-full border-2 border-blue-200 bg-gradient-to-br from-blue-500 to-blue-700 p-3 shadow-lg'
          }
        >
          <Stethoscope size={24} className="text-white" />
        </div>
      )}
      <div
        className={
          `relative group max-w-[85%] rounded-2xl p-4 shadow-lg transition-all duration-200 ` +
          (message.isError
            ? isStaff
              ? 'rounded-tl-md border border-red-500/40 bg-red-500/10 text-red-200'
              : 'rounded-tl-md border border-red-200 bg-red-50 text-red-800'
            : isUser
              ? 'rounded-tr-md bg-gradient-to-br from-blue-500 to-blue-300 text-white'
              : isStaff
                ? 'rounded-tl-md border border-slate-700/50 bg-slate-800/95 text-slate-200'
                : 'rounded-tl-md border border-gray-100 bg-white text-gray-800')
        }
      >
        <div
          className={`mb-1 pb-1 text-xs font-medium ${
            isUser ? 'text-primary-100' : isStaff ? 'text-slate-500' : 'text-gray-400'
          }`}
          style={{ letterSpacing: '0.02em' }}
        >
          {isUser ? 'You' : 'Healthcare Assistant'} • {formatTime(message.timestamp)}
        </div>
        {/* File preview for uploads */}
        {isUser && isImage && (
          <div className="mb-2">
            <button
              type="button"
              className="focus:outline-none"
              onClick={() => onPreviewClick && message.fileUrl && message.fileType && message.fileName && onPreviewClick(message.fileUrl, message.fileType, message.fileName)}
            >
              <img src={message.fileUrl} alt={message.fileName || 'Uploaded image'} className="max-h-40 rounded shadow border hover:scale-105 transition-transform" />
            </button>
            <div className="text-xs text-gray-200 mt-1 truncate">{message.fileName}</div>
            {(showUploadProgress || analyzing) && (
              <div className="mt-2 w-full space-y-1">
                {showUploadProgress && (
                  <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                    <div className="h-full bg-primary-500 transition-all duration-300" style={{ width: `${uploadProgress}%` }} />
                  </div>
                )}
                {analyzing && (
                  <p className="text-xs text-gray-300">Analyzing...</p>
                )}
              </div>
            )}
          </div>
        )}
        {isUser && isPDF && (
          <div className="mb-2">
            {hasPdfThumbnail ? (
              <button
                type="button"
                className="flex flex-col items-center focus:outline-none"
                onClick={() => onPreviewClick && message.fileUrl && message.fileType && message.fileName && onPreviewClick(message.fileUrl, message.fileType, message.fileName)}
              >
                <img src={message.pdfThumbnail} alt={message.fileName || 'PDF preview'} className="max-h-32 rounded shadow border mb-1" />
                <span className="text-xs text-gray-200 truncate">{message.fileName}</span>
              </button>
            ) : (
              <button
                type="button"
                className="flex items-center gap-2 focus:outline-none"
                onClick={() => onPreviewClick && message.fileUrl && message.fileType && message.fileName && onPreviewClick(message.fileUrl, message.fileType, message.fileName)}
              >
                <FileText size={28} className="text-primary-200" />
                <span className="text-xs text-gray-200 truncate">{message.fileName}</span>
              </button>
            )}
            {(showUploadProgress || analyzing) && (
              <div className="mt-2 w-full space-y-1">
                {showUploadProgress && (
                  <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                    <div className="h-full bg-primary-500 transition-all duration-300" style={{ width: `${uploadProgress}%` }} />
                  </div>
                )}
                {analyzing && (
                  <p className="text-xs text-gray-300">Analyzing...</p>
                )}
              </div>
            )}
          </div>
        )}
        {isUser ? (
          message.content ? <p className="whitespace-pre-wrap text-base leading-relaxed content-stable streaming-content">{message.content}</p> : null
        ) : (
          <>
            <div
              className={`staff-report-prose streaming-content content-stable max-w-none text-sm ${
                isStaff ? 'text-slate-300' : 'text-gray-700'
              }`}
              style={{ wordWrap: 'break-word' }}
            >
              <ReactMarkdown components={markdownComponents}>{message.content}</ReactMarkdown>
            </div>
            {/* Download/Copy buttons for assistant messages */}
            <div className="relative mt-2 flex justify-end gap-1">
              <button
                type="button"
                className={`rounded p-1 ${isStaff ? 'text-slate-400 hover:bg-slate-700/80 hover:text-slate-200' : 'hover:bg-primary-100'}`}
                title="Download as PDF"
                onClick={handleDownloadPDF}
              >
                <Download size={16} />
              </button>
              <button
                type="button"
                className={`rounded p-1 ${isStaff ? 'text-slate-400 hover:bg-slate-700/80 hover:text-slate-200' : 'hover:bg-primary-100'}`}
                title="Download as Text"
                onClick={handleDownloadText}
              >
                <FileText size={16} />
              </button>
              <div className="relative">
                <button
                  type="button"
                  className={`rounded p-1 ${isStaff ? 'text-slate-400 hover:bg-slate-700/80 hover:text-slate-200' : 'hover:bg-primary-100'}`}
                  title="Copy to Clipboard"
                  onClick={handleCopy}
                >
                  <Copy size={16} />
                </button>
                {copied && (
                  <span className="absolute -top-7 left-1/2 z-10 -translate-x-1/2 whitespace-nowrap rounded bg-primary-600 px-2 py-1 text-xs text-white shadow">
                    Copied!
                  </span>
                )}
              </div>
            </div>
          </>
        )}
        {isUser && onEdit && (
          <button
            className="absolute top-2 right-2 text-white-700 hover:text-green-400"
            title="Edit message"
            aria-label="Edit message"
            onClick={() => onEdit(message.id)}
          >
            <Pencil size={16} />
          </button>
        )}
      </div>
      {isUser && (
        <div className="flex-shrink-0 bg-primary-500 rounded-full p-2 shadow-md border-2 border-primary-600">
          <Smile size={24} className="text-white" />
        </div>
      )}
    </div>
  );
};

export default ChatMessage;