import React, { useEffect, useRef, useState } from 'react';
import { Bot, BotIcon, UserCircle, FileText, Download, Copy } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Message } from '../types';
import { formatTime } from '../utils/date';
import jsPDF from 'jspdf';

interface ChatMessageProps {
  message: Message;
  onPreviewClick?: (fileUrl: string, fileType: string, fileName: string) => void;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message, onPreviewClick }) => {
  const isUser = message.role === 'user';
  // File preview logic
  const isImage = message.fileUrl && message.fileType && message.fileType.startsWith('image/');
  const isPDF = message.fileType === 'application/pdf';
  const hasPdfThumbnail = !!message.pdfThumbnail;
  const messageRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);

  // Fade-in animation on mount
  useEffect(() => {
    if (messageRef.current) {
      messageRef.current.classList.add('fade-in');
    }
  }, []);

  useEffect(() => {
    if (copied) {
      const timer = setTimeout(() => setCopied(false), 1200);
      return () => clearTimeout(timer);
    }
  }, [copied]);
  
  // Helper to get formatted date/time
  const getFormattedDate = () => {
    const d = new Date(message.timestamp);
    return d.toLocaleString();
  };
  // Helper to get topic or file name
  const getTopic = () => {
    if (message.fileName) return message.fileName;
    return '';
  };
  // Download as PDF
  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text('Healthcare Assistant Interpretation', 10, 15);
    doc.setFontSize(10);
    doc.text(`Date: ${getFormattedDate()}`, 10, 25);
    const topic = getTopic();
    if (topic) doc.text(`Session/Topic: ${topic}`, 10, 32);
    doc.setFontSize(12);
    doc.text('---', 10, 40);
    doc.text(message.content, 10, 50, { maxWidth: 180 });
    doc.setFontSize(10);
    doc.text('---', 10, 270);
    doc.text('This summary was generated by an AI healthcare assistant for informational purposes only.', 10, 278, { maxWidth: 180 });
    doc.save(`AI-Interpretation-${message.id}.pdf`);
  };
  // Download as text
  const handleDownloadText = () => {
    const lines = [
      'Healthcare Assistant Interpretation',
      `Date: ${getFormattedDate()}`,
      getTopic() ? `Session/Topic: ${getTopic()}` : '',
      '---',
      message.content,
      '---',
      'This summary was generated by an AI healthcare assistant for informational purposes only.'
    ].filter(Boolean).join('\n');
    const blob = new Blob([lines], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AI-Interpretation-${message.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };
  // Copy to clipboard
  const handleCopy = () => {
    navigator.clipboard.writeText(message.content);
    setCopied(true);
  };
  
  return (
    <div
      ref={messageRef}
      className={`flex items-start space-x-3 ${isUser ? 'justify-end' : ''} mb-3`}
      style={{ animation: 'fadeInUp 0.5s' }}
    >
      {!isUser && (
        <div className="flex-shrink-0 bg-primary-100 rounded-full p-2 shadow-md border-2 border-primary-200">
          <Bot size={24} className="text-primary-600" />
        </div>
      )}
      <div
        className={
          `p-4 rounded-2xl max-w-[85%] relative group shadow-lg transition-all duration-200 ` +
          `${isUser ? 'bg-primary-500 text-white rounded-tr-md' : 'bg-primary-50 text-gray-800 rounded-tl-md'} ` +
          `${message.isError ? 'bg-accent-100 text-accent-800 border border-accent-300' : ''}`
        }
      >
        <div className={`pb-1 mb-1 text-xs font-medium ${isUser ? 'text-primary-100' : 'text-gray-400'}`}
          style={{ letterSpacing: '0.02em' }}
        >
          {isUser ? 'You' : 'Healthcare Assistant'} • {formatTime(message.timestamp)}
        </div>
        {/* File preview for uploads */}
        {isUser && isImage && (
          <div className="mb-2">
            <button
              type="button"
              className="focus:outline-none"
              onClick={() => onPreviewClick && message.fileUrl && message.fileType && message.fileName && onPreviewClick(message.fileUrl, message.fileType, message.fileName)}
            >
              <img src={message.fileUrl} alt={message.fileName || 'Uploaded image'} className="max-h-40 rounded shadow border hover:scale-105 transition-transform" />
            </button>
            <div className="text-xs text-gray-200 mt-1 truncate">{message.fileName}</div>
          </div>
        )}
        {isUser && isPDF && (
          hasPdfThumbnail ? (
            <button
              type="button"
              className="mb-2 flex flex-col items-center focus:outline-none"
              onClick={() => onPreviewClick && message.fileUrl && message.fileType && message.fileName && onPreviewClick(message.fileUrl, message.fileType, message.fileName)}
            >
              <img src={message.pdfThumbnail} alt={message.fileName || 'PDF preview'} className="max-h-32 rounded shadow border mb-1" />
              <span className="text-xs text-gray-200 truncate">{message.fileName}</span>
            </button>
          ) : (
            <button
              type="button"
              className="mb-2 flex items-center gap-2 focus:outline-none"
              onClick={() => onPreviewClick && message.fileUrl && message.fileType && message.fileName && onPreviewClick(message.fileUrl, message.fileType, message.fileName)}
            >
              <FileText size={28} className="text-primary-200" />
              <span className="text-xs text-gray-200 truncate">{message.fileName}</span>
            </button>
          )
        )}
        {isUser ? (
          message.content ? <p className="whitespace-pre-wrap text-base leading-relaxed">{message.content}</p> : null
        ) : (
          <>
            <div className="prose prose-sm max-w-none">
              <ReactMarkdown
                components={{
                  a: ({node, ...props}) => <a {...props} className="text-blue-600 underline" target="_blank" rel="noopener noreferrer" />
                }}
              >
                {message.content}
              </ReactMarkdown>
            </div>
            {/* Download/Copy buttons for assistant messages */}
            <div className="flex gap-1 mt-2 justify-end relative">
              <button
                className="p-1 rounded hover:bg-primary-100"
                title="Download as PDF"
                onClick={handleDownloadPDF}
              >
                <Download size={16} />
              </button>
              <button
                className="p-1 rounded hover:bg-primary-100"
                title="Download as Text"
                onClick={handleDownloadText}
              >
                <FileText size={16} />
              </button>
              <div className="relative">
                <button
                  className="p-1 rounded hover:bg-primary-100"
                  title="Copy to Clipboard"
                  onClick={handleCopy}
                >
                  <Copy size={16} />
                </button>
                {copied && (
                  <span className="absolute -top-7 left-1/2 -translate-x-1/2 bg-primary-600 text-white text-xs px-2 py-1 rounded shadow z-10 whitespace-nowrap">
                    Copied!
                  </span>
                )}
              </div>
            </div>
          </>
        )}
      </div>
      {isUser && (
        <div className="flex-shrink-0 bg-primary-500 rounded-full p-2 shadow-md border-2 border-primary-300">
          <UserCircle size={24} className="text-white" />
        </div>
      )}
    </div>
  );
};

export default ChatMessage;