import jsPDF from 'jspdf';

export type StaffReportType = 'radiology' | 'lab' | 'general';

export interface StaffReportPdfOptions {
  content: string;
  reportType: StaffReportType;
  messageId: string;
  timestamp: string | Date;
  sourceFileName?: string;
  /** Source imaging study shown in the PDF (radiology reports). */
  referenceImage?: {
    url?: string;
    dataUrl?: string;
    label?: string;
  };
}

const REPORT_META: Record<
  StaffReportType,
  { title: string; subtitle: string; department: string; accent: [number, number, number]; filenamePrefix: string }
> = {
  radiology: {
    title: 'Radiology AI Interpretation Report',
    subtitle: 'Medical Imaging Analysis — For Healthcare Professional Use',
    department: 'Radiology / Medical Imaging',
    accent: [49, 46, 129],
    filenamePrefix: 'Radiology-AI-Report',
  },
  lab: {
    title: 'Laboratory AI Interpretation Report',
    subtitle: 'Diagnostic Laboratory Analysis — For Healthcare Professional Use',
    department: 'Laboratory Medicine',
    accent: [4, 120, 87],
    filenamePrefix: 'Laboratory-AI-Report',
  },
  general: {
    title: 'Clinical AI Interpretation Report',
    subtitle: 'AI-Assisted Clinical Summary — For Healthcare Professional Use',
    department: 'Clinical Decision Support',
    accent: [30, 64, 175],
    filenamePrefix: 'Clinical-AI-Report',
  },
};

const PAGE = { margin: 18, width: 210, height: 297, footerY: 282 };
const CONTENT_WIDTH = PAGE.width - PAGE.margin * 2;

const DISCLAIMER =
  'This document was generated by an AI clinical decision-support assistant. It is intended to support—not replace—professional medical judgment. Verify all findings against source studies, institutional protocols, and direct patient assessment before clinical action.';

function formatTimestamp(ts: string | Date): string {
  const d = typeof ts === 'string' ? new Date(ts) : ts;
  return d.toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function stripInlineMarkdown(text: string): string {
  return normalizeTextForPdf(
    text
      .replace(/\*\*(.+?)\*\*/g, '$1')
      .replace(/\*(.+?)\*/g, '$1')
      .replace(/__(.+?)__/g, '$1')
      .replace(/_(.+?)_/g, '$1')
      .replace(/`(.+?)`/g, '$1')
      .trim()
  );
}

/**
 * jsPDF Helvetica only supports WinAnsi/Latin-1. Unicode (μ, en-dash, etc.) causes
 * garbled output with spaces between every character — normalize before rendering.
 */
function normalizeTextForPdf(text: string): string {
  let s = text.normalize('NFKC');

  const replacements: Array<[RegExp, string]> = [
    [/[\u03BC\u00B5]/g, 'u'], // μ, µ → u (e.g. uIU/mL)
    [/[\u2013\u2014\u2212]/g, '-'], // en/em dash, minus
    [/[\u2018\u2019]/g, "'"],
    [/[\u201C\u201D]/g, '"'],
    [/[\u00A0]/g, ' '],
    [/[\u200B-\u200D\uFEFF]/g, ''], // zero-width
    [/[\u00B0]/g, ' deg'],
    [/[\u00B1]/g, '+/-'],
    [/[\u2264]/g, '<='],
    [/[\u2265]/g, '>='],
    [/[\u2192]/g, '->'],
    [/[\u00D7]/g, 'x'],
  ];

  for (const [pattern, replacement] of replacements) {
    s = s.replace(pattern, replacement);
  }

  // Strip remaining non-WinAnsi characters (decompose accented Latin where possible)
  s = s.replace(/[^\t\n\r\x20-\x7E\xA0-\xFF]/g, (ch) => {
    const base = ch.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    return /^[\x20-\x7E]$/.test(base) ? base : '';
  });

  return s.replace(/[ \t]{2,}/g, ' ').trim();
}

type Block =
  | { kind: 'h2'; text: string }
  | { kind: 'h3'; text: string }
  | { kind: 'bullet'; text: string; level: number }
  | { kind: 'paragraph'; text: string };

function parseContentToBlocks(content: string): Block[] {
  const blocks: Block[] = [];
  const lines = content.split(/\r?\n/);

  for (const raw of lines) {
    const line = raw.trimEnd();
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (/^##\s+/.test(trimmed)) {
      blocks.push({ kind: 'h2', text: stripInlineMarkdown(trimmed.replace(/^##\s+/, '')) });
      continue;
    }
    if (/^###\s+/.test(trimmed)) {
      blocks.push({ kind: 'h3', text: stripInlineMarkdown(trimmed.replace(/^###\s+/, '')) });
      continue;
    }
    if (/^[-*•]\s+/.test(trimmed)) {
      const level = /^\s{2,}/.test(line) ? 1 : 0;
      blocks.push({ kind: 'bullet', text: stripInlineMarkdown(trimmed.replace(/^[-*•]\s+/, '')), level });
      continue;
    }
    if (/^\d+\.\s+/.test(trimmed)) {
      blocks.push({ kind: 'bullet', text: stripInlineMarkdown(trimmed.replace(/^\d+\.\s+/, '')), level: 0 });
      continue;
    }
    blocks.push({ kind: 'paragraph', text: stripInlineMarkdown(trimmed) });
  }

  return blocks;
}

function drawPageFooter(doc: jsPDF, pageNum: number, totalPages: number, orgName: string) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(orgName, PAGE.margin, PAGE.footerY);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE.width - PAGE.margin, PAGE.footerY, { align: 'right' });
}

function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE.footerY - 8) {
    doc.addPage();
    return PAGE.margin + 8;
  }
  return y;
}

async function resolveReferenceImageDataUrl(
  referenceImage?: StaffReportPdfOptions['referenceImage']
): Promise<string | null> {
  if (!referenceImage) return null;
  if (referenceImage.dataUrl) return referenceImage.dataUrl;
  if (!referenceImage.url) return null;
  try {
    const res = await fetch(referenceImage.url);
    const blob = await res.blob();
    return await new Promise<string | null>((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(typeof reader.result === 'string' ? reader.result : null);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function drawReferenceImageSection(
  doc: jsPDF,
  y: number,
  dataUrl: string,
  label: string | undefined,
  accent: [number, number, number]
): number {
  const format = dataUrl.startsWith('data:image/png') ? 'PNG' : 'JPEG';
  let props: { width: number; height: number };
  try {
    props = doc.getImageProperties(dataUrl);
  } catch {
    return y;
  }

  const maxHmm = 105;
  let imgWmm = CONTENT_WIDTH;
  let imgHmm = (props.height * imgWmm) / props.width;
  if (imgHmm > maxHmm) {
    imgHmm = maxHmm;
    imgWmm = (props.width * imgHmm) / props.height;
  }

  y = ensureSpace(doc, y, imgHmm + 18);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...accent);
  doc.text('REFERENCE IMAGE (SOURCE STUDY)', PAGE.margin, y);
  y += 6;

  if (label) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    const labelLines = doc.splitTextToSize(normalizeTextForPdf(label), CONTENT_WIDTH);
    doc.text(labelLines, PAGE.margin, y);
    y += labelLines.length * 4 + 2;
  }

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.3);
  doc.rect(PAGE.margin, y - 1, imgWmm, imgHmm);
  doc.addImage(dataUrl, format, PAGE.margin, y, imgWmm, imgHmm, undefined, 'FAST');
  y += imgHmm + 8;

  doc.setDrawColor(...accent);
  doc.setLineWidth(0.4);
  doc.line(PAGE.margin, y, PAGE.width - PAGE.margin, y);
  y += 8;

  return y;
}

function renderStaffInterpretationPdf(doc: jsPDF, options: StaffReportPdfOptions, referenceDataUrl: string | null): void {
  const meta = REPORT_META[options.reportType];
  const blocks = parseContentToBlocks(options.content);
  const reportId = options.messageId.slice(0, 12).toUpperCase();
  const generatedAt = formatTimestamp(options.timestamp);

  let y = PAGE.margin;

  // Header band
  doc.setFillColor(...meta.accent);
  doc.rect(0, 0, PAGE.width, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('Acufore Health', PAGE.margin, 12);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(normalizeTextForPdf(meta.department), PAGE.margin, 19);
  doc.setFontSize(8);
  doc.text(`Report ID: ${reportId}`, PAGE.width - PAGE.margin, 12, { align: 'right' });
  doc.text(generatedAt, PAGE.width - PAGE.margin, 19, { align: 'right' });

  y = 36;
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  const titleLines = doc.splitTextToSize(meta.title, CONTENT_WIDTH);
  doc.text(titleLines, PAGE.margin, y);
  y += titleLines.length * 6 + 2;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(normalizeTextForPdf(meta.subtitle), PAGE.margin, y);
  y += 8;

  // Metadata box
  doc.setDrawColor(203, 213, 225);
  doc.setFillColor(248, 250, 252);
  const metaRows: [string, string][] = [
    ['Generated', generatedAt],
    ['Report ID', reportId],
    ['Department', meta.department],
  ];
  if (options.sourceFileName) {
    metaRows.push(['Source document', options.sourceFileName]);
  }
  const boxH = 6 + metaRows.length * 7;
  doc.roundedRect(PAGE.margin, y, CONTENT_WIDTH, boxH, 2, 2, 'FD');
  let metaY = y + 5;
  doc.setFontSize(9);
  for (const [label, value] of metaRows) {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(51, 65, 85);
    doc.text(`${label}:`, PAGE.margin + 4, metaY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 41, 59);
    const valueLines = doc.splitTextToSize(normalizeTextForPdf(value), CONTENT_WIDTH - 42);
    doc.text(valueLines, PAGE.margin + 38, metaY);
    metaY += Math.max(7, valueLines.length * 4.5);
  }
  y += boxH + 6;

  // Divider
  doc.setDrawColor(...meta.accent);
  doc.setLineWidth(0.4);
  doc.line(PAGE.margin, y, PAGE.width - PAGE.margin, y);
  y += 8;

  if (options.reportType === 'radiology' && referenceDataUrl) {
    y = drawReferenceImageSection(
      doc,
      y,
      referenceDataUrl,
      options.referenceImage?.label || options.sourceFileName,
      meta.accent
    );
  }

  // Body
  for (const block of blocks) {
    if (block.kind === 'h2') {
      y = ensureSpace(doc, y, 14);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(...meta.accent);
      const lines = doc.splitTextToSize(block.text.toUpperCase(), CONTENT_WIDTH);
      doc.text(lines, PAGE.margin, y);
      y += lines.length * 5.5 + 3;
      continue;
    }

    if (block.kind === 'h3') {
      y = ensureSpace(doc, y, 12);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(30, 41, 59);
      const lines = doc.splitTextToSize(block.text, CONTENT_WIDTH);
      doc.text(lines, PAGE.margin, y);
      y += lines.length * 5 + 2;
      continue;
    }

    if (block.kind === 'bullet') {
      const indent = block.level > 0 ? 6 : 0;
      const bulletX = PAGE.margin + indent;
      const textX = bulletX + 4;
      const textWidth = CONTENT_WIDTH - indent - 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(51, 65, 85);
      const lines = doc.splitTextToSize(block.text, textWidth);
      y = ensureSpace(doc, y, lines.length * 4.8 + 2);
      doc.setFillColor(...meta.accent);
      doc.circle(bulletX + 1, y - 1.2, 0.7, 'F');
      doc.text(lines, textX, y);
      y += lines.length * 4.8 + 1.5;
      continue;
    }

    // paragraph
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const lines = doc.splitTextToSize(block.text, CONTENT_WIDTH);
    y = ensureSpace(doc, y, lines.length * 4.8 + 2);
    doc.text(lines, PAGE.margin, y);
    y += lines.length * 4.8 + 3;
  }

  // Disclaimer block
  y = ensureSpace(doc, y, 28);
  doc.setDrawColor(203, 213, 225);
  doc.setFillColor(241, 245, 249);
  const discLines = doc.splitTextToSize(DISCLAIMER, CONTENT_WIDTH - 8);
  const discH = discLines.length * 4.2 + 10;
  doc.roundedRect(PAGE.margin, y, CONTENT_WIDTH, discH, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('IMPORTANT NOTICE', PAGE.margin + 4, y + 6);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(discLines, PAGE.margin + 4, y + 11);

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawPageFooter(doc, p, totalPages, 'Acufore Health — Confidential');
  }

  const dateSlug = new Date(options.timestamp).toISOString().split('T')[0];
  doc.save(`${meta.filenamePrefix}_${dateSlug}_${reportId}.pdf`);
}

/**
 * Renders a standardized clinical interpretation PDF for radiology and laboratory staff chat.
 */
export function downloadStaffInterpretationPdf(options: StaffReportPdfOptions): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  renderStaffInterpretationPdf(doc, options, null);
}

/** Async variant — embeds reference imaging for radiology when a source image URL is provided. */
export async function downloadStaffInterpretationPdfAsync(
  options: StaffReportPdfOptions
): Promise<void> {
  let referenceDataUrl: string | null = null;
  if (options.reportType === 'radiology' && options.referenceImage) {
    referenceDataUrl = await resolveReferenceImageDataUrl(options.referenceImage);
  }
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  renderStaffInterpretationPdf(doc, options, referenceDataUrl);
}

type MessageWithFile = {
  id: string;
  role: string;
  fileUrl?: string;
  fileType?: string;
  fileName?: string;
  pdfThumbnail?: string;
};

/** Nearest prior user upload (image or PDF preview) for an assistant interpretation message. */
export function findReferenceImageForAssistantMessage(
  messages: MessageWithFile[],
  assistantMessageId: string
): { url: string; label?: string } | undefined {
  const idx = messages.findIndex((m) => m.id === assistantMessageId);
  if (idx <= 0) return undefined;
  for (let i = idx - 1; i >= 0; i--) {
    const m = messages[i];
    if (m.role !== 'user') continue;
    if (m.fileUrl && m.fileType?.startsWith('image/')) {
      return { url: m.fileUrl, label: m.fileName };
    }
    if (m.pdfThumbnail) {
      return { url: m.pdfThumbnail, label: m.fileName };
    }
  }
  return undefined;
}

export function buildStaffReportPlainText(options: StaffReportPdfOptions): string {
  const meta = REPORT_META[options.reportType];
  const reportId = options.messageId.slice(0, 12).toUpperCase();
  const lines = [
    'ACUFORE HEALTH',
    meta.title,
    meta.subtitle,
    '',
    `Generated: ${formatTimestamp(options.timestamp)}`,
    `Report ID: ${reportId}`,
    `Department: ${meta.department}`,
  ];
  if (options.sourceFileName) {
    lines.push(`Source document: ${options.sourceFileName}`);
  }
  lines.push('', '─'.repeat(60), '', options.content, '', '─'.repeat(60), '', DISCLAIMER);
  return lines.join('\n');
}
